# This function is made to avoid boiler plate
# code and clean the None values from the dict
# generated by Namespace objects returned by
# argparse.parse_args(), those needed to be
# transformed in a dict object and also contains
# a bunch of None values from the others parameters.
#
# Example: 
#       
# [In]: {
#       
#           'write': 'someparam',
#           'read': None,
#           'clearSession': None,
#           'clearStats': None,
#           'outputStats': None,
#           'beginAssembly': None,
#           'printFullSaveList': None,
#           'removePartialSave': None
# }
#
#       
# [Out]: {
#         'write': 'someparam' 
# }
def valid_args(parser_object) -> dict:
    data = vars(parser_object)
    cleaned_data = {}
    for key, value in data.items():
        if value != None:
            cleaned_data[key] = value

    return cleaned_data
